// AUTO-GENERATED by scripts/build-environment.mjs (--test) — do not edit by hand.
export const environment = {
  production: false,
  apiBaseUrl: "http://localhost:8000/api/v1",
  appName: "bms-frontend",
};
