// AUTO-GENERATED by scripts/build-environment.mjs (--prod) — do not edit by hand.
export const environment = {
  production: true,
  apiBaseUrl: "http://localhost:8000/api/v1",
  appName: "bms-frontend",
};
